# Generated by Django 5.1.2 on 2024-10-31 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Demo", "0002_alter_mdemo_options_mdemo_text"),
        ("Resource", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mdemo",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_images",
                to="Resource.mimage",
                verbose_name="图片",
            ),
        ),
    ]
